[package]
name = "wildbird"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-expand = "1.0.52"
once_cell = "1.17.1"
wildbird_macro_derive = {path = "./bin/wildbird_macro_derive" }


[workspace]
members = [
    "./bin/wildbird_macro_derive"
]