[package]
name = "wildbird"
version = "0.0.4"
edition = "2021"
description = "Rust Framework"
license = "MIT"
rust-version = "1.70"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wildbird_macro_derive = { path = "./bin/wildbird_macro_derive", version = "0.0.4" }

[dev-dependencies]
cargo-expand = "1.0.48"

[workspace]
members = [
    "./bin/wildbird_macro_derive"
]

[profile.dev]
opt-level = 0
debug = 0
incremental = true

[profile.release]
opt-level = 3
debug = 0
lto = "thin"