[package]
name = "wildbird"
version = "0.0.1"
edition = "2021"
description = "Rust Framework"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-expand = "1.0.52"
once_cell = "1.17.1"
wildbird_macro_derive = {path = "./bin/wildbird_macro_derive" }


[workspace]
members = [
    "./bin/wildbird_macro_derive"
]

[profile.dev]
opt-level = 0
debug = 0
incremental = true

[profile.release]
opt-level = 3
debug = 0
lto = "thin"