[package]
name = "wildbird_macro_derive"
version = "0.1.0"
edition = "2021"
description = "Rust Framework | Macro System"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.15", features = ['full'] }
proc-macro2 = "1.0.56"
quote = "1.0.27"
once_cell = "1.17.1"