[package]
name = "wildbird_macro_derive"
version = "0.0.11"
edition = "2021"
description = "Rust Framework 🐦 | Macro System"
license = "MIT"
rust-version = "1.70"
repository = "https://github.com/PawelJastrzebski/wildbird.rs"
categories = ["data-structures", "development-tools"]
keywords = [
    "lazy",
    "static",
    "async",
    "framework",
    "dependency",
    "inject",
    "macros",
    "service",
    "singleton"
]

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.18", features = ['full'] }
quote = "1.0.28"

[profile.dev]
opt-level = 0
debug = 0
incremental = true

[profile.release]
opt-level = 3
debug = 0
lto = "thin"